CREATE OR REPLACE DATABASE ANTHROPIC_TOOL_USE_DB;
CREATE OR REPLACE SCHEMA ANTHROPIC_TOOL_USE_DB.TOOL_SCHEMA;
CREATE WAREHOUSE ANTHROPIC_TOOL_USE_WH_XS
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Create role for container runtime
CREATE ROLE IF NOT EXISTS ANTHROPIC_TOOL_USE_ROLE;
GRANT ROLE ANTHROPIC_TOOL_USE_ROLE TO USER <YOUR USER>;

-- Grant necessary privileges
GRANT USAGE ON DATABASE ANTHROPIC_TOOL_USE_DB TO ROLE ANTHROPIC_TOOL_USE_ROLE;
GRANT ALL ON SCHEMA ANTHROPIC_TOOL_USE_DB.TOOL_SCHEMA TO ROLE ANTHROPIC_TOOL_USE_ROLE;
GRANT USAGE ON WAREHOUSE ANTHROPIC_TOOL_USE_WH_XS TO ROLE ANTHROPIC_TOOL_USE_ROLE;

-- Create network rule for external access
CREATE NETWORK RULE IF NOT EXISTS WEATHERAPI_ACCESS
  TYPE = 'HOST_PORT'
  MODE = 'EGRESS'
  VALUE_LIST = ('api.weatherapi.com');

-- Create external access integration
CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS WEATHERAPI_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (WEATHERAPI_ACCESS)
  ENABLED = true;

GRANT USAGE ON INTEGRATION WEATHERAPI_ACCESS_INTEGRATION TO ROLE ANTHROPIC_TOOL_USE_ROLE;

USE ROLE ANTHROPIC_TOOL_USE_ROLE;